# deployment for spring boot microservice service-registry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: service-registry
      project: bootcamp115
  template:
    metadata:
      labels:
        app: service-registry
        project: bootcamp115
    spec:
      containers:
        - name: service-registry-container
          image: ghcr.io/ishtiaqsamdani007/bc-115-backend-service-registry
          imagePullPolicy: Always
          ports:
            - containerPort: 8761       
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-registry

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: https://bc115be.spcluster.tk/eureka/

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://3.128.171.66:30001/minet?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      
            - name: SPRING_DATASOURCE_PASSWORD
              value: Bootcamp@115!

            - name: SPRING_FLYWAY_ENABLED
              value: "false"
      
      imagePullSecrets:
        - name: my-docker-secret