apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      project: bootcamp115
  template:
    metadata:
      labels:
        app: frontend
        project: bootcamp115
    spec:
      containers:
        - name: frontend-pod
          image: ghcr.io/ishtiaqsamdani007/bc115-fe
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 30
            periodSeconds: 30
      imagePullSecrets:
      - name: my-docker-secret